name: Web Deploy Manual

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'env'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

concurrency:
  group: web-${{ inputs.environment }}-manual # デプロイ先が1つしかないため repo 内で排他制御
  cancel-in-progress: true # PR の更新があった場合は前のジョブをキャンセルする

jobs:
  web-build-and-deploy-manual:
    environment:
      name: ${{ inputs.environment }}
      url: ${{ vars.BASE_URL }}

    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    env:
      ASSUME_ROLE: ${{ inputs.environment == 'production' && 'arn:aws:iam::158677943024:role/github_cube-unit.net_web_deploy_production' || 'arn:aws:iam::158677943024:role/github_cube-unit.net_web_deploy_staging' }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
        with:
          aqua_version: v2.56.6

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3.0.0
        with:
          hugo-version: '0.123.7'

      - name: Build (Productions)
        if: inputs.environment == 'production'
        working-directory: web
        run: hugo --minify

      - name: Build (Staging)
        if: inputs.environment != 'production'
        working-directory: web
        run: hugo --baseURL "${{ vars.BASE_URL }}"

      - uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          role-to-assume: ${{ env.ASSUME_ROLE }}
          aws-region: ap-northeast-1

      - name: Deploy
        working-directory: web
        run: aws s3 sync --delete public ${{ vars.S3_URL }}

      - name: Purge Cache - Cloudfront
        run: aws cloudfront create-invalidation --distribution-id ${{vars.DISTRIBUTION_ID}} --paths "/*"

      - name: Purge Cache - Cloudflare
        uses: jakejarvis/cloudflare-purge-action@eee6dba0236093358f25bb1581bd615dc8b3d8e3 # v0.3.0
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_CACHE_PURGE_API_TOKEN }}
          PURGE_URLS: '["${{ vars.BASE_URL }}", "${{ vars.BASE_URL }}/"]'
